name: Bug report
description: Create a bug report for Ignition Concept.
labels: ['no status']
body:
  - type: markdown
    attributes:
      value: "## Thank you for contributing to my project!"
  - type: markdown
    attributes:
      value: "##### What Package Is You Currently Facing Error?"
  - type: input
    attributes:
      label: "Package Name"
      description: "check if the issuse has already arised"
      placeholder: package@x.x.x / package@tag
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: "Steps to reproduce"
      value: |
        Steps:
        1.
        2.
        3.
  - type: textarea
    attributes:
      label: Current behavior
      description: Describe what happens instead of the expected behavior.
  - type: textarea
    attributes:
      label: Expected behavior
      description: Describe what should happen.
  - type: checkboxes
    attributes:
      label: Which Package Scope For?
      description: You may select more than one.
      options:
      - label: php
      - label: javascript
      - label: typescript
